// <auto-generated />
using System;
using AppEjemplo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AppEjemplo.Migrations
{
    [DbContext(typeof(ClaimsDbContext))]
    [Migration("20190412211612_ClaimsInitial")]
    partial class ClaimsInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AppEjemplo.Models.Claims", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("claim_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AuthorizationNumber");

                    b.Property<short?>("ClaimStatus");

                    b.Property<short>("ClaimType");

                    b.Property<string>("InsurerAddress1")
                        .IsRequired()
                        .HasColumnName("insurer_address1")
                        .HasMaxLength(55);

                    b.Property<string>("InsurerAddress2")
                        .HasColumnName("insurer_address2")
                        .HasMaxLength(55);

                    b.Property<string>("InsurerCity")
                        .IsRequired()
                        .HasColumnName("insurer_city")
                        .HasMaxLength(50);

                    b.Property<int?>("InsurerId")
                        .HasColumnName("insurer_id");

                    b.Property<string>("InsurerName")
                        .IsRequired()
                        .HasColumnName("insurer_name")
                        .HasMaxLength(80);

                    b.Property<string>("InsurerState")
                        .IsRequired()
                        .HasColumnName("insurer_state")
                        .HasColumnType("character(2)");

                    b.Property<string>("InsurerZip")
                        .IsRequired()
                        .HasColumnName("insurer_zip")
                        .HasColumnType("character(12)");

                    b.Property<bool>("IsEpsdt");

                    b.Property<int>("PracticeAssociationId");

                    b.Property<int?>("RelatedClaimId");

                    b.Property<string>("SubscriberAddress1")
                        .IsRequired()
                        .HasColumnName("subscriber_address1")
                        .HasMaxLength(55);

                    b.Property<string>("SubscriberAddress2")
                        .HasColumnName("subscriber_address2")
                        .HasMaxLength(55);

                    b.Property<string>("SubscriberCity")
                        .IsRequired()
                        .HasColumnName("subscriber_city")
                        .HasMaxLength(50);

                    b.Property<DateTime>("SubscriberDOB")
                        .HasColumnName("subscriber_d_o_b")
                        .HasColumnType("date");

                    b.Property<string>("SubscriberEmployerName")
                        .IsRequired()
                        .HasColumnName("subscriber_employer_name")
                        .HasMaxLength(80);

                    b.Property<string>("SubscriberFirstName")
                        .IsRequired()
                        .HasColumnName("subscriber_first_name")
                        .HasMaxLength(35);

                    b.Property<char>("SubscriberGender")
                        .HasColumnName("subscriber_gender");

                    b.Property<string>("SubscriberId")
                        .IsRequired()
                        .HasColumnName("subscriber_id")
                        .HasMaxLength(20);

                    b.Property<string>("SubscriberLastName")
                        .IsRequired()
                        .HasColumnName("subscriber_last_name")
                        .HasMaxLength(60);

                    b.Property<char?>("SubscriberMiddleInitial")
                        .HasColumnName("subscriber_middle_initial");

                    b.Property<string>("SubscriberNameSuffix")
                        .HasColumnName("subscriber_name_suffix")
                        .HasMaxLength(10);

                    b.Property<string>("SubscriberPlanGroupNumber")
                        .IsRequired()
                        .HasColumnName("subscriber_plan_group_number")
                        .HasMaxLength(20);

                    b.Property<string>("SubscriberState")
                        .IsRequired()
                        .HasColumnName("subscriber_state")
                        .HasColumnType("character(2)");

                    b.Property<string>("SubscriberZip")
                        .IsRequired()
                        .HasColumnName("subscriber_zip")
                        .HasColumnType("character(12)");

                    b.HasKey("ClaimId")
                        .HasName("pk_claims");

                    b.ToTable("claims");
                });
#pragma warning restore 612, 618
        }
    }
}
